export enum HTTP_STATUS_CODES {
    HTTP_BAD_REQUEST = 400,
    HTTP_OK = 200,
    HTTP_UNAUTHORISED = 401,
    HTTP_INTERNAL_SERVER_ERROR = 500,
    HTTP_NOT_FOUND = 404,
    HTTP_CREATED = 201,
    HTTP_NO_CONTENT = 204
}